# Makefile
# Riesenie IJC-DU1, příklad a), 28.2.2020
# Autor: Peter Rucek, xrucek00, FIT
# GCC 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)


CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic 

tail: tail.c tail.h
	gcc tail.c $(CFALGS) -o tail

clean:
	rm tail